### ISSUE TITLE
Lah

### ISSUE THREAD

**Issue by kelilipan** [evanezcent/Selenium-Training#1]
matkul opo coy

**Comment by envictuz** [comment]
VVPL LoL.
 Tubes e nggae skenario testing web

**Comment by evanezcent** [comment]
> VVPL LoL

Tubes e nggae skenario testing web

**Comment by kelilipan** [comment]
VVPL opo iku

**Comment by envictuz** [comment]
Verifikasi dan validasi perangkat lunak
